### ISSUE TITLE
rules.yaml not affecting timeline view

### ISSUE THREAD

**Issue by calbon2702** [mirrorweb/pywb#78]
## Expected behavior
```
    # uk gov utm rule
    - url_prefix: uk,gov,www)/government/publications/reporting-requirements-for-medicine-shortages-and-discontinuations
      fuzzy_lookup: 
        re_type: sub
        match: '[?&]utm_[^=]+=[^&]+(?=&|$)'
        replace: ''
```

Should adding this code to rules.yaml replace the UTM parameters on this URL:
https:/www.gov.uk/government/publications/reporting-requirements-for-medicine-shortages-and-discontinuations?utm_medium=email&utm_campaign=govuk-notifications-topic&utm_source=9db305b6-aec1-4c37-884e-961ad0f717e8&utm_content=daily

## What actually happened
1. Rules added to rules.yaml (TNA)
2. Ran local environment (http://localhost:8080/*/https://www.gov.uk/government/publications/reporting-requirements-for-medicine-shortages-and-discontinuations?utm_source=9db305b6-aec1-4c37-884e-961ad0f717e8?utm_medium=email&utm_campaign=govuk-notifications-topic&utm_source=9db305b6-aec1-4c37-884e-961ad0f717e8&utm_content=daily)
3. Has no affect on the URL

## Browser
Chrome

![image](https://github.com/mirrorweb/pywb/assets/60651886/dd1f6041-6d47-4aa9-a873-f3f2ed161c1e)
